// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.API.Models.Context;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(StockAPIDBContext))]
    [Migration("20240818132943_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.API.Models.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("691f2028-c1f7-40d3-bc66-403630a73941"),
                            Count = 10,
                            ProductId = new Guid("021ed5d7-b5e0-44d4-a9b8-1efdada32594")
                        },
                        new
                        {
                            Id = new Guid("816cf5e1-1e54-425d-8d58-0491e3a121a6"),
                            Count = 5,
                            ProductId = new Guid("840e2dab-c5b1-43e4-8f61-dea1e007afe9")
                        },
                        new
                        {
                            Id = new Guid("635d528b-cfcd-4a14-b46a-7beb009babe5"),
                            Count = 2,
                            ProductId = new Guid("34c6a3a5-4f37-4d59-9c6f-bc8bcfc86816")
                        },
                        new
                        {
                            Id = new Guid("305fcb3d-2eb3-4660-a135-7c287638f09f"),
                            Count = 4,
                            ProductId = new Guid("dafa94ed-6ab2-4eb9-b081-0ff320712ccc")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
